# Generated by Django 5.1 on 2024-09-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_location',
            new_name='born_location',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
