# Generated by Django 5.1 on 2024-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articles_options_articles_name_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name_author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
