# Generated by Django 5.1 on 2024-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
